#SPDX-FileCopyrightText: 2023 Birger Schacht
#SPDX-License-Identifier: MIT
# Works only on PRs at the moment
name: Run gitlint

on:
  workflow_call:
    inputs:
      ignore:
        required: false
        type: string
        # B6: body-is-missing
        # B5: body-min-length
        default: "B6,B5"
      contrib:
        required: false
        type: string
        default: "contrib-title-conventional-commits"
      basebranch:
        required: false
        type: string
        default: "main"
      arguments:
        required: false
        type: string
        default: "-c body-max-line-length.line-length=120"
      comment:
        required: false
        type: boolean
        default: true

jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Extract branch name
        run: echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Install gitlint
        run: sudo apt-get -y install gitlint
      - name: Run gitlint
        run: |
          gitlint ${{inputs.arguments}} --fail-without-commits --contrib ${{inputs.contrib}} --ignore ${{inputs.ignore}} --commits origin/${{inputs.basebranch}}..origin/$GIT_BRANCH
        id: gitlint
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for your contribution! ⚠️ there seems to be a problem with your commit messages - they should adhere to the [https://conventionalcommits.org](conventionalcommits) specification. Please fix that!'
            })
        if: ${{ failure() && steps.gitlint.conclusion == 'failure' && inputs.comment }}
